# Generated by Django 4.2.26 on 2025-11-19 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Schedule configuration (days, time, frequency, etc.)', verbose_name='schedule')),
                ('streak_count', models.IntegerField(default=0, verbose_name='streak count')),
                ('last_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='last completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
                'db_table': 'habits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'last_completed_at'], name='habits_user_id_8a970f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsAggregate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('focus_seconds', models.IntegerField(default=0, verbose_name='focus seconds')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='tasks completed')),
                ('habits_completed', models.IntegerField(default=0, verbose_name='habits completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_aggregates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'analytics aggregate',
                'verbose_name_plural': 'analytics aggregates',
                'db_table': 'analytics_aggregates',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_a_user_id_87cee3_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
