# Generated by Django 4.2.26 on 2025-11-19 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Calculated duration of the session in seconds', verbose_name='duration (seconds)')),
                ('interruptions', models.IntegerField(default=0, verbose_name='interruptions')),
                ('completed', models.BooleanField(default=False, help_text='Whether the session was completed successfully', verbose_name='completed')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.task', verbose_name='task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'focus session',
                'verbose_name_plural': 'focus sessions',
                'db_table': 'focus_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='focus_sessi_user_id_078ffa_idx'), models.Index(fields=['-started_at'], name='focus_sessi_started_66fc95_idx')],
            },
        ),
    ]
